name: Bug report
description: Report a reproducible problem.
title: "[bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide complete reproduction details.
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: v3.0.0 / artifact filename
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: Windows 11 / macOS 14 / Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: 1. ... 2. ... 3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / errors
      render: shell
